### PR TITLE
Solution for #162

### PR DESCRIPTION
**Pull request by TIANGeng708**
I tried to change the sorting logic a little bit.  Added the ability to sort using second priority.  #162

### CODE REVIEW

**Comment by SubhamTyagi** [comment]
Could you explain What this PR will do?

**Comment by TIANGeng708** [comment]
If we sort apps by size, there will always be different apps with the same size, and sometimes there will be many apps with the same size.  In my modification, these apps with the same size will be sorted by the recent use time.

**Comment by 2catycm** [comment]
good idea

**Comment by SubhamTyagi** [comment]
@TIANGeng708 Could you again reopen this PR. I accidentally rebased this PR instead of squashing it.

**Comment by TIANGeng708** [comment]
@SubhamTyagi  Sorry, I do not know what to do. Do you mean that I need to create a new PR?

**Comment by TIANGeng708** [comment]
@2catycm Thank you!

**Comment by SubhamTyagi** [comment]
> @SubhamTyagi Sorry, I do not know what to do. Do you mean that I need to create a new PR?

Yes you have to Create a new PR.

**Pull request merged**
